# SELECT P.ID, P.PARENT_ID, C.ID
# FROM ECOLI_DATA AS P
# LEFT JOIN ECOLI_DATA AS C
# ON P.ID = C.PARENT_ID
# # WHERE P.PARENT_ID IS NULL

SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (
    SELECT C.ID AS ID
    FROM ECOLI_DATA AS P
    LEFT JOIN ECOLI_DATA AS C
    ON P.ID = C.PARENT_ID
    WHERE P.PARENT_ID IS NULL
)
