-- 코드를 입력하세요
#음식종류별
#즐겨찾기수가 가장 많은 식당
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO AS A JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS B ON A.FOOD_TYPE = B.FOOD_TYPE
WHERE A.FAVORITES = B.FAVORITES
ORDER BY FOOD_TYPE DESC