SELECT ID,
    CASE 
        WHEN RANKED_SIZE <= 0.25 THEN "CRITICAL"
        WHEN RANKED_SIZE <= 0.5 THEN "HIGH"
        WHEN RANKED_SIZE <= 0.75 THEN "MEDIUM"
        WHEN RANKED_SIZE <= 1 THEN "LOW"
    END AS COLONY_NAME
FROM (
    SELECT ID, SIZE_OF_COLONY, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKED_SIZE
    FROM ECOLI_DATA
    ORDER BY ID
) AS A