#1. LEFT JOIN (왼쪽을 기준으로 오른쪽 테이블에 매칭되는 행이 있으면 매칭, 나머지는 NULL)
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A
LEFT JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME
LIMIT 3

# #2. NOT EXISTS (서브쿼리의 결과, 즉 행이 존재하지 않을 경우)
# SELECT A.NAME, A.DATETIME
# FROM ANIMAL_INS AS A
# WHERE NOT EXISTS (
#     SELECT 1 FROM ANIMAL_OUTS AS B
#     WHERE A.ANIMAL_ID = B.ANIMAL_ID
# )
# ORDER BY DATETIME
# LIMIT 3

# #3. NOT IN (ANIMAL_INS에서 뽑은 ID가 ANIMAL_OUTS에서 뽑은 ID에 없을 때)
# SELECT NAME, DATETIME
# FROM ANIMAL_INS
# WHERE ANIMAL_ID NOT IN (
#     SELECT ANIMAL_ID FROM ANIMAL_OUTS
# )
# ORDER BY DATETIME
# LIMIT 3;
