SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR

#1. HOUR의 중요성 (숫자임)
#2. DATE_FORMAT은 문자열이라서 숫자 변환이 필요 (+0)

# SELECT DATE_FORMAT(DATETIME, '%k')+0 AS HOUR, COUNT(*) AS COUNT
# FROM ANIMAL_OUTS
# WHERE DATE_FORMAT(DATETIME, '%k') BETWEEN '9' AND '19'
# GROUP BY DATE_FORMAT(DATETIME, '%k')
# ORDER BY DATE_FORMAT(DATETIME, '%k')